apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-api-db-pv
  namespace: go-api-server
  labels:
    type: psql
#  namespace: psql-ns

spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/k8s/kub
    type: DirectoryOrCreate


