apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-api-db-pvc
#  namespace: psql-ns

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



