apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-api-db-pvc
  namespace: go-api-server

spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



