apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-api-db-sts
#  namespace: psql-ns
  labels:
    app: go-api-db-sts


spec:
  serviceName: go-api-db-svc
  replicas: 1

  selector:
    matchLabels:
      app: psql

  template:
    metadata:
      labels:
        app: psql

    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: go-api-db-pvc

      containers:
        - name: postgresql
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: go-api-db-secret
            - configMapRef:
                name: go-api-db-config

          ports:
            - containerPort: 5432
              name: postgresql

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres




