apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-db-configmap
{{/*  namespace: {{ .Values.namespace }}*/}}

data:
  POSTGRES_DB: {{ required "POSTGRES_DB not set" .Values.database.POSTGRES_DB }}

