apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chart.fullname" . }}-db-secrets
  namespace: {{ .Values.namespace }}

data:
  POSTGRES_USER: {{ required "POSTGRES_USER not set" .Values.database.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ required "POSTGRES_PASSWORD not set" .Values.database.POSTGRES_PASSWORD }}

