apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-db-svc
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: psql

  type: {{ .Values.service.database.type }}

  ports:
    - port: {{ .Values.service.database.port }}
      targetPort: {{ .Values.service.database.port }}


