docker_database:
  POSTGRESQL_ADDON_HOST: 10.104.186.119
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: go_app_db
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret

current_db:
  RUNNING: docker_database