apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-backend-depl
  labels:
    app: {{ include "chart.fullname" . }}-backend-depl

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-server

  template:
    metadata:
      labels:
        app: go-server

    spec:
      restartPolicy: Always
      containers:
        - name: go-image
          image: {{ .Values.image.backend.repository }}:{{.Values.image.backend.tag }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}






