apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-api-client-ingress
  namespace: go-api-server

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-api-client-svc
                port:
                  number: 8081


