apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server

    spec:
      containers:
        - name: go-image
          image: mokhlesur96/go-app:9d3c88f757cb58efb1327a4d04d0d4bd6cff33cc
          ports:
            - containerPort: 8081



