apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql

    spec:
      containers:
        - name: psql
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: psql-config

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: psql-secret
                  optional: false

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: psql-secret
                  optional: false

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: psql-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: psql-data
          hostPath:
            path: /database/data/



