apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-depl
  namespace:

spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql

    spec:
      containers:
        - name: psql
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: go_app_db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: psql-data
              mountPath: /var/lib/postgresql/data


      volumes:
        - name: psql-data
          hostPath:
            path: /database/data/



