apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    app: psql
#  namespace: psql-ns

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/mokhlesurrahman/dev/db_pv


