apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
#  namespace: psql-ns

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  selector:
    matchLabels:
      app: psql


