apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
#  namespace: psql-ns

spec:
  volumeName: psql-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi