apiVersion: ENC[AES256_GCM,data:hB8=,iv:ceHqKdV5Pd0R27S9QNiVZ8cFeUuzkUAs/EoUuWJejmw=,tag:K3q05x0geiw6hVYBm6A2Lw==,type:str]
kind: ENC[AES256_GCM,data:3xtSoWF/,iv:ZoIBvwAtwpBlmzPDZteGfSujxj9BRFpe8p8HPgeQ5xw=,tag:ENxPcPIZ/ZfzRmVEFgzkJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yUfDdcWy3zo=,iv:7FB2w/8Le9vr52fSxf1OD6RLhpYOF39oWpDDNhsE+w4=,tag:cNipppimlYcWqRebJv/nbw==,type:str]
type: ENC[AES256_GCM,data:ledG2GoA,iv:iXXVKeSvo49pwbNCfb/HD9d6Ym4u1gAc4zXGPVAENVE=,tag:nzG20vUUedPuEuiMpAp/mg==,type:str]
data:
    password: ENC[AES256_GCM,data:jv1j6KXeTI0=,iv:l2MPZeumQOVOfMplKC+VWB231zp4U37mG0cViIccgyo=,tag:RdqEoAwPJf0uO5rEsbPmlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-25T08:29:07Z"
    mac: ENC[AES256_GCM,data:YmOc0FcwzneXkCoqKJh4VJ8zMSW9bC8Q8zaZH1fhxd5tXJc2SXfH4Fz0/T7g5Z8hkIRWeO7rN0icgCYVYFj7iCdVWkuAAYQtwTH2RYSIe3Neork7eLBuXri5GWTpNTeCGNEds92WWMnIhGFuiIlUm/vVjcAQpoFfn5r7GTDVvlM=,iv:7A73vYCvpBXDVjwBJlGmKF7IeTYL3SXR5jSBMAPHb7M=,tag:p4NG4ul0NjBsxfLSaBv+fQ==,type:str]
    pgp:
        - created_at: "2023-04-25T08:28:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyguKhvMWmz+AQ/+Io86+Atwypdm/+wC54xphoibW85200DnzURdNIsaFL1N
            GECSdZp7r67cuvqqmLKIZB5OmtqxvsamN/gmXkFEhM3pi8DcVSutqH+tXt6cRfMc
            7A4c9u3liKVeBmJTlljHY9FJX7/NGgwQ9gg8fzaGllsv4s2s1kzMmlW00GphXgvD
            9nO0CVbE6v93hPCADpN7nvqlbNQbmQgX6D8Wl3pykSaMbNmWqV2UVmtM2wFglK8Y
            RuAVd5Ows7o6Y1fw6L6ibXDSfPgX+zBVDOEF4d+Js+eRabe49APxYkZSQjFsyc4M
            kZ0MCnVdu525RnH3bYEQ0lSGUG3pxaKVbKRvoEu9r1ts5QuyZE/sKMHt4UMLoJV9
            GC92DlYj0OcQKI78iDWWoBTw74jStmvKL0MsgQfsSaYWGWcdrwLI44mtn5jm4jub
            zeJk7V+bq8EwyL1F5yvXibpNv6UWLfu2kArtuRk5LfTaxrQYK3NkuT6M+mk9CgEt
            +BAnJVqoWbOi5v4SKqQV3FP634sNaulGhuxsd7CXgqNk0JDRdtTuxfx5+eJbfQU4
            ut4MeUmKiJGkN20U1njy9a+Q3qgRi3PuTt0esV+JGM2hVkY2d2hmd8PfPV5Ib6il
            wgs7QYiSK4lFpW51zFfSHVqe9DC7dmv82/zPwAT+RwNaDZZ2WVL/YPDn+dVjRjvU
            aAEJAhBLbyBe/Fw7jWUVFwCSvQwR5wiWovW7ZnlpY2nctbXZV1D42r1ApUpDy3Eh
            zfv7q4NpyXV0w3wDRW6kOvppIAlvlzkEmyEMewWg7u2lRPGNVXOlNlBVAT7yc4rX
            1s1rGgYy57PT
            =tf4M
            -----END PGP MESSAGE-----
          fp: DF53F9E9CE2900EBFE78C37556F8C068C89B80AC
    unencrypted_suffix: _unencrypted
    version: 3.7.3
