name: test-ci

on:
  push:
    branches: 
      - develop
      - main 
  pull_request:
    branches: 
      - main
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    steps:
      - name: Checkoout to latest code 
        uses: actions/checkout@v2

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: "v0.153.1"

      - name: Install helm-secrets plugin
        run: helm plugin install https://github.com/jkroepke/helm-secrets --version 3.9.0

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: '3.7.3'
        id: install

#      - name: Install and import GnuPG(GPG)
#        run: |
#          sudo apt-get install gnupg
#          gpg --import deployment/chart/values/development/public.key
#          gpg --list-keys
        


      - name: Test Version
        run: |
          sops --version
          helmfile --version 
          helm version 
          kubectl version --client
          gpg --key-list
          sops --pgp DF53F9E9CE2900EBFE78C37556F8C068C89B80AC -d deployment/chart/values/development/encrypted_secrets2.yaml > deployment/chart/values/development/encrypted_secrets3.yaml
          cat deployment/chart/values/development/encrypted_secrets3.yaml

      - name: Helmfile linter
        run: helmfile lint -f deployment/chart/helmfile.yaml

      - name: Helm linter
        run: helm lint -f deployment/chart/Chart.yaml


      - name: Build the golang application 
        run: go build -o main .

  merge:
    name: Merge to Main 
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 

      - name: Echo Hello
        run: echo "Hello from the main branch"
  
  deploy:
    name: Deploy to production 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Echo confirming we are on main branch 
        run: echo "switched to main branch"

      - name: Push built file to docker repository
        run: echo "Pushing image to dockerhub repository"

      - name: Checkout to code
        uses: actions/checkout@v3

      - name: Building and Pushing docker image 
        run: |
          go build -o main .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_KEY }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go-app:$GITHUB_SHA .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/go-app:$GITHUB_SHA

  common: 
    name: Git Information
    runs-on: ubuntu-latest
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 
          echo "Current branch is ${{github.ref}}"
          echo "Event name is ${{github.event_name}}"



