name: test-ci

on:
  push:
    branches: 
      - develop
      - main 
  pull_request:
    branches: 
      - main
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    steps:
      - name: Checkoout to latest code 
        uses: actions/checkout@v2

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: "v0.153.1"

      - name: Install helm-secrets plugin
        run: helm plugin install https://github.com/jkroepke/helm-secrets --version 3.9.0

      - name: Install sops
        run: |
          sudo mkdir -p /src/sops/
          sudo chown -R $USER:$USER /src/sops
          cd /src/sops
          git clone https://github.com/mozilla/sops.git
          cd sops/
          git checkout develop
          make install
          sops --version

      - name: Test Version
        run: |
          helmfile --version 
          helm version 
          kubectl version --client

      - name: Helmfile linter
        run: helmfile lint -f deployment/chart/helmfile.yaml

      - name: Helm linter
        run: helm lint -f deployment/chart/Chart.yaml


      - name: Build the golang application 
        run: go build -o main .

  merge:
    name: Merge to Main 
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 

      - name: Echo Hello
        run: echo "Hello from the main branch"
  
  deploy:
    name: Deploy to production 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Echo confirming we are on main branch 
        run: echo "switched to main branch"

      - name: Push built file to docker repository
        run: echo "Pushing image to dockerhub repository"

      - name: Checkout to code
        uses: actions/checkout@v3

      - name: Building and Pushing docker image 
        run: |
          go build -o main .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_KEY }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go-app:$GITHUB_SHA .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/go-app:$GITHUB_SHA

  common: 
    name: Git Information
    runs-on: ubuntu-latest
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 
          echo "Current branch is ${{github.ref}}"
          echo "Event name is ${{github.event_name}}"



