name: test-ci

on:
  push:
    branches: 
    - develop
    - Main
  pull_request:
    branches: ["main"]
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 
          echo "Current branch is ${{github.ref}}"
          echo "Event name is ${{github.event_name}}"
          echo "Event name is ${{github.head_ref}}"

      - name: Checkoout to latest code 
        uses: actions/checkout@v2


      - name: Build the golang application 
        run: go build -o main .


  merge:
    name: Merge to Main 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 
          echo "Current branch is ${{github.ref}}"
          echo "Event name is ${{github.event_name}}"
          echo "Event name is ${{github.head_ref}}"
          echo "DONE"


      - name: Echo Hello
        run: echo "Hello from the main branch"
  


