name: test-ci

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main"]
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Echo A Simple String
        run: echo "This is test github ci" 

      - name: Checkoout to latest code 
        uses: actions/checkout@v2


      - name: Build the golang application 
        run: go build -o main .


  merge:
    name: Merge to Main 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
    steps:
      - name: Echo World
        run: echo "World from the main branch"
  
  develop:
    name: Develop branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    steps:
      - name: Echo Hello
        run: echo "Hello from the develop branch"


