name: test-ci

on:
  push:
    branches: 
      - develop
      - main 
  pull_request:
    branches: 
      - main
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    steps:
      - name: Checkoout to latest code 
        uses: actions/checkout@v2

      - name: Build the golang application 
        run: go build -o main .


  merge:
    name: Merge to Main 
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 

      - name: Echo Hello
        run: echo "Hello from the main branch"
  
  deploy:
    name: Deploy to production 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Echo confirming we are on main branch 
        run: echo "swiched to main branch"

  common: 
    name: Git Information
    runs-on: ubuntu-latest
    steps:
      - name: Echo A Simple String
        run: | 
          echo "This is test github ci" 
          echo "Current branch is ${{github.ref}}"
          echo "Event name is ${{github.event_name}}"



