name: test-ci

on:
  push:
    branches: ["develop"]
  
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Echo A Simple String
        run: echo "This is test github ci" 

